package com.test.oracle.dao;

import com.test.oracle.model.Computer;

public interface ComputerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FMAD_AIRPLANE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FMAD_AIRPLANE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    int insert(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FMAD_AIRPLANE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    int insertSelective(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FMAD_AIRPLANE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    Computer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FMAD_AIRPLANE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    int updateByPrimaryKeySelective(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FMAD_AIRPLANE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    int updateByPrimaryKey(Computer record);
}