package com.example.oracle.model;

import java.util.Date;

public class Computer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.ID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.UUID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.CREATE_TIME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.UPDATE_TIME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.NAME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.CODE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.AIRPLANE_TYPE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private String airplaneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.MIN_SEATS
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private Short minSeats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.MAX_SEATS
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private Short maxSeats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.AIRPLANE_COMPANY_ID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private Long airplaneCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FMAD_AIRPLANE.SIMPLE_NAME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    private String simpleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.ID
     *
     * @return the value of T_FMAD_AIRPLANE.ID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.ID
     *
     * @param id the value for T_FMAD_AIRPLANE.ID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.UUID
     *
     * @return the value of T_FMAD_AIRPLANE.UUID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.UUID
     *
     * @param uuid the value for T_FMAD_AIRPLANE.UUID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.CREATE_TIME
     *
     * @return the value of T_FMAD_AIRPLANE.CREATE_TIME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.CREATE_TIME
     *
     * @param createTime the value for T_FMAD_AIRPLANE.CREATE_TIME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.UPDATE_TIME
     *
     * @return the value of T_FMAD_AIRPLANE.UPDATE_TIME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.UPDATE_TIME
     *
     * @param updateTime the value for T_FMAD_AIRPLANE.UPDATE_TIME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.NAME
     *
     * @return the value of T_FMAD_AIRPLANE.NAME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.NAME
     *
     * @param name the value for T_FMAD_AIRPLANE.NAME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.CODE
     *
     * @return the value of T_FMAD_AIRPLANE.CODE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.CODE
     *
     * @param code the value for T_FMAD_AIRPLANE.CODE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.AIRPLANE_TYPE
     *
     * @return the value of T_FMAD_AIRPLANE.AIRPLANE_TYPE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public String getAirplaneType() {
        return airplaneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.AIRPLANE_TYPE
     *
     * @param airplaneType the value for T_FMAD_AIRPLANE.AIRPLANE_TYPE
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setAirplaneType(String airplaneType) {
        this.airplaneType = airplaneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.MIN_SEATS
     *
     * @return the value of T_FMAD_AIRPLANE.MIN_SEATS
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public Short getMinSeats() {
        return minSeats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.MIN_SEATS
     *
     * @param minSeats the value for T_FMAD_AIRPLANE.MIN_SEATS
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setMinSeats(Short minSeats) {
        this.minSeats = minSeats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.MAX_SEATS
     *
     * @return the value of T_FMAD_AIRPLANE.MAX_SEATS
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public Short getMaxSeats() {
        return maxSeats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.MAX_SEATS
     *
     * @param maxSeats the value for T_FMAD_AIRPLANE.MAX_SEATS
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setMaxSeats(Short maxSeats) {
        this.maxSeats = maxSeats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.AIRPLANE_COMPANY_ID
     *
     * @return the value of T_FMAD_AIRPLANE.AIRPLANE_COMPANY_ID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public Long getAirplaneCompanyId() {
        return airplaneCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.AIRPLANE_COMPANY_ID
     *
     * @param airplaneCompanyId the value for T_FMAD_AIRPLANE.AIRPLANE_COMPANY_ID
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setAirplaneCompanyId(Long airplaneCompanyId) {
        this.airplaneCompanyId = airplaneCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FMAD_AIRPLANE.SIMPLE_NAME
     *
     * @return the value of T_FMAD_AIRPLANE.SIMPLE_NAME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FMAD_AIRPLANE.SIMPLE_NAME
     *
     * @param simpleName the value for T_FMAD_AIRPLANE.SIMPLE_NAME
     *
     * @mbggenerated Wed Nov 11 11:53:31 CST 2015
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName;
    }
}